apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django-svc
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: django-application
    tier: app

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: staticfiles-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/static"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staticfiles-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: staticfiles-pv

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  selector:
    matchLabels:
      app: django-application
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django-application
        tier: app
    spec:
      volumes:
        - name: staticfiles
          persistentVolumeClaim: 
            claimName: staticfiles-pvc
      containers:
        - image: django-app:latest
          imagePullPolicy: Always
          name: django-app
          env:
            - name: POSTGRES_DB
              value: project
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
          ports:
            - containerPort: 8000
          volumeMounts: 
            - mountPath: "/data/static"
              name: staticfiles
              